[package]
name = "neat"
version = "0.1.0"
authors = ["Alec Deason <alec50@tinycountry.com>"]
edition = "2018"

[dependencies]
rand = "0.6.0-pre.1"
rand_xorshift = "0.1.1"
petgraph = "0.4.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pancurses = "0.16"
rayon = "1.0"
